name: Build PrismLauncher Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          qt-version: '6.8.3'
          build-type: Release

      - name: Configure
        shell: cmd
        run: |
          cmake --preset windows_msvc

      - name: Build
        shell: cmd
        run: |
          cmake --build --preset windows_msvc --config Release

      - name: Install PrismLauncher
        shell: cmd
        run: |
          cmake --install build --config Release --prefix artifact

      - name: Create ZIP
        shell: powershell
        run: |
          Compress-Archive `
            -Path artifact\* `
            -DestinationPath PrismLauncher-Windows.zip

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: PrismLauncher-Windows
          path: PrismLauncher-Windows.zip